/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * Clase EditarUsuario permite gestionar la edición de datos de usuarios registrados
 * a través de una interfaz gráfica, incluyendo nombre, correo, usuario y contraseña.
 *
 * @author MI EQUIPO
 */
public class EditarUsuario extends javax.swing.JFrame {
private jPanelListaUsuarios panelListaUsuarios;
   private String correoSeleccionado;
    private String usuarioSeleccionado;
    
    /**
     * Constructor por defecto que inicializa los componentes gráficos.
     */
    public EditarUsuario() {
        initComponents();
    }
    
    /**
     * Constructor que recibe el panel de usuarios y datos seleccionados para edición.
     *
     * @param panelListaUsuarios Panel donde se muestra la lista de usuarios.
     * @param correo Correo del usuario a editar.
     * @param usuario Nombre de usuario a editar.
     */
    public EditarUsuario(jPanelListaUsuarios panelListaUsuarios, String correo, String usuario) {
        initComponents();
        setLocationRelativeTo(null);

        if (panelListaUsuarios == null) {
            JOptionPane.showMessageDialog(this, "El panel de usuarios no está disponible.");
            return;
        }

        this.panelListaUsuarios = panelListaUsuarios;
        this.usuarioSeleccionado = usuario;
        this.correoSeleccionado = correo;

        // Cargar los datos del usuario
        cargarDatosUsuario();
    }
     /**
     * Carga los datos del usuario seleccionado desde un archivo de texto y
     * los muestra en los campos correspondientes.
     */
     private void cargarDatosUsuario() {
        String ruta = "C:\\Users\\hp\\Documents\\2024\\SEGUNDO SEMESTRE\\METODOS Y TALLER DE PROGRAMACION\\Proyecto Netbeans\\Gestion de Tareas\\usuarioscreados.txt";
        try (BufferedReader reader = new BufferedReader(new FileReader(ruta))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(";");

                // Verificar que sea el usuario seleccionado
                if (datos[1].equals(correoSeleccionado) && datos[2].equals(usuarioSeleccionado)) {
                    // Llenar los campos con los datos correspondientes
                    txtNombreCrearUsuario.setText(datos[0]);  // Nombre y Apellido
                    txtCorreoCrearUsuario.setText(datos[1]);  // Correo
                    txtUsuarioCrearUsuario.setText(datos[2]); // Usuario
                    jContraseñaCrearUsuario.setText(datos[3]); // Contraseña
                    break;  // No necesitamos seguir buscando, ya encontramos al usuario
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos del usuario: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCrearUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreoCrearUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioCrearUsuario = new javax.swing.JTextField();
        btnSalirEditarUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jContraseñaCrearUsuario = new javax.swing.JPasswordField();
        btnEditarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Nombre y apellidos:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Nombre de Usuario:");

        btnSalirEditarUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnSalirEditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalirEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirEditarUsuario.setText("Salir");
        btnSalirEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEditarUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Contraseña:");

        btnEditarUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnEditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar Usuario");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Editar Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Datos del usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalirEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuarioCrearUsuario)
                                .addComponent(jLabel6)
                                .addComponent(jContraseñaCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(85, 248, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jContraseñaCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalirEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método para manejar el evento de cierre de la ventana.
     * Cierra la ventana actual.
     */
    private void btnSalirEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEditarUsuarioActionPerformed
        // Cerrar la ventana de CrearUsuario
        this.dispose(); // Cierra la ventana de CrearUsuario

    }//GEN-LAST:event_btnSalirEditarUsuarioActionPerformed

    /**
     * Método para manejar el evento de edición del usuario.
     * Valida los campos, actualiza el archivo de usuarios y refresca la lista.
     */
    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
   // Obtenemos los datos de los campos
    String nombre = txtNombreCrearUsuario.getText();
    String correo = txtCorreoCrearUsuario.getText();
    String usuario = txtUsuarioCrearUsuario.getText();
    String contrasena = new String(jContraseñaCrearUsuario.getPassword());

    // Verifica que todos los campos estén completos
    if (nombre.isEmpty() || correo.isEmpty() || usuario.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return;
    }

    // Ruta al archivo de usuarios existentes
    String ruta = "C:\\Users\\hp\\Documents\\2024\\SEGUNDO SEMESTRE\\METODOS Y TALLER DE PROGRAMACION\\Proyecto Netbeans\\Gestion de Tareas\\usuarioscreados.txt";
    File archivo = new File(ruta);

    // Crear un StringBuilder para almacenar el nuevo contenido del archivo
    StringBuilder nuevoContenido = new StringBuilder();

    try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
        String linea;
        boolean usuarioEditado = false;

        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split(";");
            
            // Aquí se usa el nombre de usuario original (que se cargó al abrir la ventana)
            if (datos.length >= 4 && datos[2].equals(usuarioSeleccionado)) {  // Compara el nombre de usuario original
                // Si encuentra el usuario, reemplaza la línea con los nuevos datos
                nuevoContenido.append(nombre).append(";")
                        .append(correo).append(";")
                        .append(usuario).append(";")
                        .append(contrasena).append("\n");
                usuarioEditado = true;
            } else {
                nuevoContenido.append(linea).append("\n");  // Escribe las líneas sin cambios
            }
        }

        // Verifica si se encontró el usuario para editar
        if (!usuarioEditado) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
            return;
        }

        // Sobrescribir el archivo original con el nuevo contenido
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
            writer.write(nuevoContenido.toString());
        }

        // Actualiza la tabla en jPanelListaUsuarios
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                panelListaUsuarios.cargarUsuariosEnTabla(); // Llama al método que actualiza la tabla
                panelListaUsuarios.revalidate();
                panelListaUsuarios.repaint();
            }
        });

        // Cierra la ventana de edición
        this.dispose();
        JOptionPane.showMessageDialog(this, "Usuario editado con éxito.");

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al editar el usuario: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

   /**
     * Método principal para ejecutar la aplicación.
     *
     * @param args Argumentos de la línea de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnSalirEditarUsuario;
    private javax.swing.JPasswordField jContraseñaCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreoCrearUsuario;
    private javax.swing.JTextField txtNombreCrearUsuario;
    private javax.swing.JTextField txtUsuarioCrearUsuario;
    // End of variables declaration//GEN-END:variables
}
