/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * Clase que representa la interfaz de inicio de sesión para usuarios y administradores.
 * Proporciona funcionalidad para verificar credenciales y redirigir a las secciones correspondientes.
 * 
 * @author MI EQUIPO
 */
public class LoginInterfaz extends javax.swing.JFrame {

    /**
     * Crea una nueva instancia de LoginInterfaz.
     * Inicializa los componentes gráficos y centra la ventana.
     */
    public LoginInterfaz() {
        
        initComponents();
        setLocationRelativeTo(null);
        
    }
    /**
     * Verifica las credenciales del administrador.
     * 
     * @param correo el correo electrónico ingresado.
     * @param contraseña la contraseña ingresada.
     * @return true si las credenciales coinciden con las del administrador; false en caso contrario.
     */
    private boolean verificarAdmin(String correo, String contraseña) {
        try (BufferedReader reader = new BufferedReader(new FileReader("admin.txt"))) {
            String linea = reader.readLine();
            if (linea != null) {
                String[] partes = linea.split(",");
                return partes[0].equals(correo) && partes[1].equals(contraseña);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo de administrador", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
    /**
     * Verifica las credenciales de un usuario normal.
     * 
     * @param correo el correo electrónico ingresado.
     * @param contraseña la contraseña ingresada.
     * @return true si las credenciales coinciden con las de un usuario registrado; false en caso contrario.
     */
    private boolean verificarUsuario(String correo, String contraseña) {
        try (BufferedReader reader = new BufferedReader(new FileReader("usuarios.txt"))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes[0].equals(correo) && partes[1].equals(contraseña)) {
                    return true;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo de usuarios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(0, 51, 153));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, 140, 60));

        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(0, 51, 153));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, 140, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Gmail :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Contraseña :");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jContraseña)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGmail, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 430, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenidos a TareaNet!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 410, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LoginFondo.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de clic en el botón "Registrarse".
     * Abre la ventana de registro y cierra la ventana actual.
     * 
     * @param evt el evento de acción asociado al botón.
     */
    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
      
        Registrarse ventanaRegistro = new Registrarse();
        ventanaRegistro.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * Maneja el evento de clic en el botón "Iniciar Sesión".
     * Verifica las credenciales ingresadas y redirige al usuario o administrador según corresponda.
     * 
     * @param evt el evento de acción asociado al botón.
     */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
    String gmail = txtGmail.getText().trim();
    String password = new String(jContraseña.getPassword()).trim();

    // Validar que ambos campos estén llenos
    if (gmail.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar su Gmail y contraseña", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean loginExitoso = false;
    boolean esAdmin = false;
    String nombreUsuario = "";
    
    // Verificar si es el administrador
    try (BufferedReader adminReader = new BufferedReader(new FileReader("C:\\Users\\hp\\Documents\\2024\\SEGUNDO SEMESTRE\\METODOS Y TALLER DE PROGRAMACION\\Proyecto Netbeans\\Gestion de Tareas\\admin.txt"))) {
        String lineaAdmin = adminReader.readLine();
        if (lineaAdmin != null) {
            String[] datosAdmin = lineaAdmin.split(",");
            if (datosAdmin[0].equals(gmail) && datosAdmin[1].equals(password)) {
                loginExitoso = true;
                esAdmin = true;
                nombreUsuario = "Administrador";
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer el archivo de administrador", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Si no es admin, verificar en usuarios normales
    if (!esAdmin) {
        try (BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\hp\\Documents\\2024\\SEGUNDO SEMESTRE\\METODOS Y TALLER DE PROGRAMACION\\Proyecto Netbeans\\Gestion de Tareas\\usuarios.txt"))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length == 3) { 
                    String archivoGmail = datos[0];
                    String archivoPassword = datos[1];
                    String archivoNombreUsuario = datos[2];

                    if (archivoGmail.equals(gmail) && archivoPassword.equals(password)) {
                        loginExitoso = true;
                        nombreUsuario = archivoNombreUsuario;
                        break;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo de usuarios", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    if (loginExitoso) {
        if (esAdmin) {
            JOptionPane.showMessageDialog(this, "Bienvenido, Administrador", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            // Mostrar el MenuPrincipal para el administrador
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Bienvenido, usuario " + nombreUsuario, "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            
            
            
        }
        this.dispose(); // Cierra la ventana de inicio de sesión actual
    } else {
        JOptionPane.showMessageDialog(this, "Gmail o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
    }




    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * Método principal para ejecutar la aplicación.
     * 
     * @param args argumentos de línea de comandos (no se usan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JPasswordField jContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField txtGmail;
    // End of variables declaration//GEN-END:variables

    private static class txtGmail {

        private static Object getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtGmail() {
        }
    }
}
